# Dracula Zsh configuration

autoload -U colors && colors

PROMPT='%F{#bd93f9}%n@%m %F{#f8f8f2}%1~ %# %f'

alias ls='ls --color=auto'
alias grep='grep --color=auto'

if [ -f /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]; then
  source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
fi